enum poll_state {
  draft
  request
  active
  completed
}

enum question_type {
  multiple_choice
  select_all
}

table answers {
  id serial [pk, not null, increment]
  question_id integer [not null]
  answer_choices text[] [not null]
}

table polls {
  id serial [pk, not null, increment]
  user_id text [not null]
  state poll_state [not null, default: 'draft']
  are_results_public boolean [not null, default: false]
  title text [not null]
  suggested_duration_days integer
  comment_to_admin text [default: `NULL`]
  created_at timestamp [not null, default: `now()`]
  begins_at timestamp [not null]
  ends_at timestamp [default: `NULL`]
}

table questions {
  id serial [pk, not null, increment]
  poll_id integer [not null]
  order integer [not null]
  question_type question_type [not null]
  question text [not null]
  answer_choices text[] [not null]
}

table user_has_done_poll {
  user_id text [not null]
  poll_id integer [not null]
}

table users {
  id serial [pk, not null, increment]
  netid text [not null, unique]
  email text [not null]
  is_admin boolean [not null, default: false]
  is_email_list boolean [not null, default: false]
}

ref: answers.question_id > questions.id

ref: polls.user_id > users.netid

ref: questions.poll_id > polls.id

ref: user_has_done_poll.poll_id > polls.id

ref: user_has_done_poll.user_id > users.netid